#!/bin/bash
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd "$root_dir"

script/build-server

docker run --rm --name minebot_server -it -p 25565:25565 minebot:dev
